// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressFillController from "./address_fill_controller"
application.register("address-fill", AddressFillController)

import SelectCheckboxesController from "./select_checkboxes_controller"
application.register("select-checkboxes", SelectCheckboxesController)
