---
require:
  - standard
  - standard-custom
  - standard-performance
  - standard-rails
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "config/environments/**"
    - "config/puma.rb"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
