---
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# be a bit kinder with our metrics
Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*
    - config/routes.rb
    - app/models/neighbour_response.rb

Metrics/MethodLength:
  Enabled: false

Metric/AbcSize:
  Exclude: 
    - app/models/neighbour_response.rb
    - app/controllers/concerns/api/error_handler.rb

Metrics/ClassLength: 
  Exclude: 
    - app/services/apis/bops/client.rb
    - app/models/neighbour_response.rb

Metrics/ParameterLists:
  Exclude: 
    - app/services/apis/bops/client.rb
    - spec/support/api_spec_helper.rb

Layout/LineLength:
  Exclude:
    - spec/**/*
    - app/services/apis/bops/client.rb

Naming/VariableNumber:
  Exclude:
    - spec/**/*

# we tend to use update_all in migrations
Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb

# Rspec
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
  Prefixes:
    - as
    - before
    - when
    - with
    - without

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb
