---
require:
  - standard
  - standard-custom
  - standard-performance
  - standard-rails
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "config/environments/**"
    - "config/puma.rb"
    - "vendor/**/*"

# TODO
Rails/EnvironmentVariableAccess:
  Exclude:
    - app/**/*

# past migrations are ignored; we don't expect to go back and edit them ever,
# we'll fix them in future migrations if at all.
Rails/BulkChangeTable:
  Exclude:
    - db/migrate/2020*
    - db/migrate/2021*
    - db/migrate/2022*

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/2020*
    - db/migrate/2021*
    - db/migrate/2022*

Rails/ThreeStateBooleanColumn:
  Exclude:
    - db/migrate/2020*
    - db/migrate/2021*
    - db/migrate/2022*
    - db/migrate/20230*
    - db/migrate/202310*
