---
services:
  db:
    image: postgres:14-bullseye
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"

  web:
    image: bops-applicants/ruby
    build: docker/ruby
    working_dir: /home/rails/bops-applicants
    init: true
    command: ["foreman", "start", "-f", "Procfile.dev"]
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432
      PROTOCOL: "http"
      PORT: 3001
      PIDFILE: "/tmp/pids/server.pid"
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - type: bind
        source: .
        target: /home/rails/bops-applicants
      - type: volume
        source: bundle
        target: /home/rails/bundle
      - type: volume
        source: node_modules
        target: /home/rails/bops-applicants/node_modules
      - type: tmpfs
        target: /tmp/pids
        tmpfs:
          mode: 0777

volumes:
  db:
  bundle:
  node_modules:
