shared:
  os_vector_tiles_api_key: <%= ENV["OS_VECTOR_TILES_API_KEY"] %>
  api_host: <%= ENV.fetch("API_HOST", "bops.localhost:3000") %>
  api_protocol: <%= ENV["PROTOCOL"] %>
  api_bearer: <%= ENV["API_BEARER"] %>
