default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bops_applicants_development

test:
  <<: *default
  database: bops_applicants_test

production:
  <<: *default
  database: bops_applicants_production
