name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install

      - name: Run Tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake
