---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle-audit:
    uses: ./.github/workflows/linters.yml
    with:
      bundler-audit: true

  brakeman:
    uses: ./.github/workflows/linters.yml
    with:
      brakeman: true

  rubocop:
    uses: ./.github/workflows/linters.yml
    with:
      rubocop: true

  biome:
    uses: ./.github/workflows/linters.yml
    with:
      biome: true

  language-versions:
    uses: ./.github/workflows/linters.yml
    with:
      language-versions: true

  specs:
    uses: ./.github/workflows/testing.yml
    strategy:
      matrix:
        specs:
          - ["models", "[a-p]*_spec.rb"]
          - ["models", "[q-z]*_spec.rb"]
          - ["controllers", "*_spec.rb"]
          - ["requests", "*_spec.rb"]
          - ["system", "[a-f]*_spec.rb"]
          - ["system", "[g-k]*_spec.rb"]
          - ["system", "[l-r]*_spec.rb"]
          - ["system", "[s-z]*_spec.rb"]
          - [
              "other",
              "*_spec.rb",
              "{components,helpers,jobs,services}",
            ]
      fail-fast: false
    with:
      name: "${{matrix.specs[0]}}: ${{matrix.specs[1]}}"
      include: "spec/${{matrix.specs[2] || matrix.specs[0]}}/**/${{matrix.specs[1]}}"
