name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install

      - name: Run linters - RuboCop
        run: |
          bundle exec rubocop --parallel

      - name: Run linters - Rome
        run: |
          git ls-files -z '*.js' '*.ts' | xargs -0 node_modules/rome/bin/rome check
          git ls-files -z '*.js' '*.ts' | xargs -0 node_modules/rome/bin/rome format

      - name: Run Tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake

      - name: Run asset pipeline
        run: |
          bundle exec rake assets:precompile
