---
name: Testing

on:
  workflow_call:
    inputs:
      exclude:
        type: string
        required: false
        default: ""
      include:
        type: string
        required: false
        default: "spec/**/*_spec.rb"
      name:
        type: string
        required: true
      test-runner:
        type: string
        default: rspec
      dockerfile:
        type: string
        required: false
        default: Dockerfile
      context:
        type: string
        required: false
        default: "."

jobs:
  tests:
    name: ${{ inputs.name }}
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install postgres client
        shell: bash
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Setup ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        if: hashFiles('yarn.lock') != ''
        with:
          node-version-file: .node-version
          cache: "yarn"

      - name: Install packages
        run: |
          yarn install --frozen-lockfile

      - name: Setup test database
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          RAILS_ENV: test
        run: |
          bundle exec rake db:create db:schema:load

      - name: Build assets
        run: bundle exec rake assets:precompile

      - name: Run rspec specs
        if: ${{ inputs.test-runner == 'rspec' }}
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          RAILS_ENV: test
          SPEC_OPTS: '-f doc  --exclude "${{ inputs.exclude }}" --pattern "${{ inputs.include }}"'
        run: |
          bundle exec rake spec

      - name: Expose GitHub Runtime for Docker build
        uses: crazy-max/ghaction-github-runtime@v3
        if: ${{ inputs.test-runner == 'docker' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ inputs.test-runner == 'docker' }}

      - name: Ensure ${{ inputs.dockerfile }} builds
        if: ${{ inputs.test-runner == 'docker' }}
        run: |
          DOCKER_BUILDKIT=1 docker buildx build \
            --cache-to type=gha,mode=max \
            --build-arg RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} -f ${{ inputs.dockerfile }} ${{ inputs.context }}
