---
name: Testing

on:
  workflow_call:
    inputs:
      exclude:
        type: string
        required: false
        default: ""
      include:
        type: string
        required: false
        default: "spec/**/*_spec.rb"
      name:
        type: string
        required: true

jobs:
  tests:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install postgres client
        shell: bash
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Setup ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        if: hashFiles('yarn.lock') != ''
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install packages
        run: |
          yarn install --frozen-lockfile

      - name: Setup test database
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          RAILS_ENV: test
        run: |
          bundle exec rake db:create db:schema:load

      - name: Build assets
        run: bundle exec rake assets:precompile

      - name: Run rspec specs
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          RAILS_ENV: test
          SPEC_OPTS: '-f doc  --exclude "${{ inputs.exclude }}" --pattern "${{ inputs.include }}"'
        run: |
          bundle exec rake spec
